[pytest]

# Settings path
DJANGO_SETTINGS_MODULE = backend.config.settings

# For apps imports
pythonpath = . backend

# Where to look for tests
testpaths = backend/apps

# Test filenames
python_files = tests.py test_*.py *_tests.py

# Django will try to reuse db instead of creating one, no migrations issues
# --reuse-db use it only locally
addopts = 
    -v
    --strict-markers 
    --tb=short
    --cov=backend
    --cov-report=term-missing
    --cov-fail-under=80 

# pytest-env allows creation of env for test purpose
env = 
    DEBUG=False

markers:
    unit: logic tests
    view: template and view test
    token: test token obtain
    posts: current user posts
    comments: comments created by current user
    user: current user data
    health: health check
    follow: current user follows
    like: current user likes
    search: other users search
    feed: feed and its actions