# Generated by Django 6.0 on 2026-02-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
    ]
