# Generated by Django 6.0.2 on 2026-02-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0006_alter_comment_id_alter_follow_id_alter_like_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.CharField(max_length=500),
        ),
    ]
