# Config file for GitHub Actions

name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest  # Fastest option

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          POSTGRES_HOST: localhost
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v6   # Copies code on VM

      - name: Set up Python
        uses: actions/setup-python@v5   # Official GitHub tool
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |            # Everything below will be treated as one line
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        env:    # Create env at virtual machine
            DJANGO_SETTINGS_MODULE: backend.config.settings # Show where is the brain of the project
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
            POSTGRES_DB: test_db
            POSTGRES_HOST: localhost
            DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
            python manage.py migrate
        

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: backend.config.settings
          PYTHONPATH: ${{ github.workspace }}  # github.workspace is a root dir, safe config
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          POSTGRES_HOST: localhost
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
            pytest --cov=backend/apps --cov-report=term-missing